# Generated by Django 4.2.4 on 2023-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_customuser_employee_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeclockBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_id', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
